name: CI_CD
on:
  push:
    tags:
      - "*"
    branches:
      - 'main'
      - 'master'

env:
  APP_NAME: jfx-native-image

jobs:
  build-jar:
    name: 'Build JAR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Java 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build JAR'
        run: |
          mvn clean package
          cp shade/$APP_NAME-*.jar shade/$APP_NAME.jar
          ls -l shade/
      - name: 'Environment'
        id: environment
        run: |
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION: $PROJECT_VERSION"
          echo ::set-output name=PROJECT_VERSION::$PROJECT_VERSION
          JAR_FILENAME=$(basename $(ls shade/$APP_NAME-*.jar))
          echo "JAR_FILENAME: $JAR_FILENAME"
          echo ::set-output name=JAR_FILENAME::$JAR_FILENAME
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: shade/${{env.APP_NAME}}.jar
      - name: 'Publish JAR to release'
        if: contains(github.ref, 'tags')
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: shade/${{ steps.environment.outputs.JAR_FILENAME }}
          tags: true
          draft: false
          overwrite: true

  build-native-image:
    name: 'Build native Image'
    needs: [build-jar]
    if: contains(github.ref, 'tags')
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - os: 'ubuntu-latest'
            label: 'linux'
            executable_extension: ''
          - os: 'macos-latest'
            label: 'macos'
            executable_extension: ''
          - os: 'windows-latest'
            label: 'windows'
            executable_extension: '.exe'
    runs-on: ${{matrix.os}}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Environment'
        id: environment
        run: |
          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION: $PROJECT_VERSION"
          echo ::set-output name=PROJECT_VERSION::$PROJECT_VERSION
        shell: bash
      - name: 'Setup Java 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build platform-specific jar
        run: |
          # overwrite pom.xml
          cp resources/pom.xml pom.xml
          mvn clean package
          cp shade/$APP_NAME-*.jar $APP_NAME.jar
        shell: bash
      - name: Display structure of downloaded files
        run: ls -l . target shade
        shell: bash
      - name: 'Set up Visual C Build Tools Workload for Visual Studio 2019 Build Tools on Windows'
        if: matrix.os == 'windows-latest'
        run: |
          choco install visualstudio2019-workload-vctools
      - name: 'Setup GraalVM Environment'
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: check java version
        run: java -version
      - name: 'Build Native Image on non-windows'
        if: matrix.os != 'windows-latest'
        run: |
          mkdir build
          cd build
          echo "build native image..."
          native-image -jar ../${{env.APP_NAME}}.jar --no-fallback -H:Name=${{env.APP_NAME}} -H:ReflectionConfigurationFiles=../resources/reflectconfig -H:JNIConfigurationFiles=../resources/jniconfig.json -H:ResourceConfigurationFiles=../resources/resourceconfig.json --allow-incomplete-classpath --verbose -H:IncludeResourceBundles=com/sun/javafx/scene/control/skin/resources/controls,com/sun/javafx/scene/control/skin/resources/controls-nt,com.sun.javafx.tk.quantum.QuantumMessagesBundle,com/sun/glass/ui/win/themes
          echo "build native image finished"
      - name: 'Build Native Image on windows'
        if: matrix.os == 'windows-latest'
        run: |
          echo "init vs2019 x64 environment"
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          echo "build native image..."
          mkdir build
          cd build
          native-image -jar ../${{env.APP_NAME}}.jar --no-fallback -H:Name=${{env.APP_NAME}} -H:ReflectionConfigurationFiles=../resources/reflectconfig -H:JNIConfigurationFiles=../resources/jniconfig.json -H:ResourceConfigurationFiles=../resources/resourceconfig.json --allow-incomplete-classpath --verbose -H:IncludeResourceBundles=com/sun/javafx/scene/control/skin/resources/controls,com/sun/javafx/scene/control/skin/resources/controls-nt,com.sun.javafx.tk.quantum.QuantumMessagesBundle,com/sun/glass/ui/win/themes
          echo "build native image finished"
        shell: cmd
      - name: Edit binary resources on windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "edit binary resources"
          ".\resources\rcedit-x64.exe" build/${{env.APP_NAME}}${{matrix.executable_extension}} --set-icon resources/app_icon.ico --set-file-version ${{ steps.environment.outputs.PROJECT_VERSION }} --set-product-version ${{ steps.environment.outputs.PROJECT_VERSION }}  --set-version-string ProductName ${{env.APP_NAME}} --set-version-string LegalCopyright MIT
        shell: bash
      - name: Prepare release files
        run: |
          7z a -tzip $APP_NAME-${{matrix.label}}-${{ steps.environment.outputs.PROJECT_VERSION }}.zip -r ./build/*
        shell: bash
      - name: 'Publish binary to release'
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{env.APP_NAME}}-${{matrix.label}}-${{ steps.environment.outputs.PROJECT_VERSION }}.zip
          tags: true
          draft: false
          overwrite: true